### ISSUE TITLE
Animator2D Animation doesn't run in Browser. (runs in-editor, though...)

### ISSUE THREAD

**Issue by Lykdraft** [layabox/LayaAir#1644] opened 2024-10-22 23:48 UTC
When running the scene in-editor, the animation runs.
But Animator2D Animation doesn't run in the  Browser.

**Comment by LayaCharley** [comment] 2024-10-26 08:23
Please provide a demo project that can reproduce the issue you reported, or a video recording showing the steps to reproduce it. During our testing, we were unable to replicate the issue you described.

**Comment by LayaCharley** [comment] 2024-10-26 08:23
> When running the scene in-editor, the animation runs. But Animator2D Animation doesn't run in the Browser.

Please provide a demo project that can reproduce the issue you reported, or a video recording showing the steps to reproduce it. During our testing, we were unable to replicate the issue you described.

**Comment by Lykdraft** [comment] 2024-10-26 13:45
Here is a screenrecord attached.


https://github.com/user-attachments/assets/ad2dabb3-0303-479d-a328-339f0f7502b0

**Comment by Lykdraft** [comment] 2024-10-26 13:47
Here's the project, zipped, Dropbox Link:
https://www.dropbox.com/scl/fi/sh1d5pf0ex6y9l1km1n4m/LayaProject-AnimDemo.zip?rlkey=ltkd8nl64tuz8tb00ec2cxhkz&dl=0

Let me know when you have it, then I can move it out of my Dropbox.

Best,
tL.

**Comment by LayaCharley** [comment] 2024-10-29 07:46
> Here's the project, zipped, Dropbox Link: https://www.dropbox.com/scl/fi/sh1d5pf0ex6y9l1km1n4m/LayaProject-AnimDemo.zip?rlkey=ltkd8nl64tuz8tb00ec2cxhkz&dl=0
> 
> Let me know when you have it, then I can move it out of my Dropbox.
> 
> Best, tL.

Thank you, we have received your demo and confirmed the issue you reported. We will address it as soon as possible and will provide you with feedback after identifying the cause of the problem.

**Comment by LayaCharley** [comment] 2024-10-29 11:44
The bug you reported has been fixed in the engine. The fix can be found in the following commit: [https://github.com/layabox/LayaAir/commit/f9bf6bb2d67296f7e34aa7b5f94b427d37d3f231](https://github.com/layabox/LayaAir/commit/f9bf6bb2d67296f7e34aa7b5f94b427d37d3f231). You can compile the engine for use, or you can download version 3.2.1 of the IDE from the LayaAir engine official website in a few days (around November 1). The download link is: [https://layaair.com/#/engineDownload](https://layaair.com/#/engineDownload).

**Comment by LayaCharley** [comment] 2024-10-29 11:44
The bug you reported has been fixed in the engine. The fix can be found in the following commit: [https://github.com/layabox/LayaAir/commit/f9bf6bb2d67296f7e34aa7b5f94b427d37d3f231](https://github.com/layabox/LayaAir/commit/f9bf6bb2d67296f7e34aa7b5f94b427d37d3f231). You can compile the engine for use, or you can download version 3.2.1 of the IDE from the LayaAir engine official website in a few days (around November 1). The download link is: [https://layaair.com/#/engineDownload](https://layaair.com/#/engineDownload).

**Closed by LayaCharley** 2024-10-29 11:44 UTC
